// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbwv1BuLpNTS1KJOUuIkU-fFr570EeL157UFNJgNyU6o254NOT11nJsBi7rIrXCLoYe-/exec";
